### ISSUE TITLE
Specify which open-source license

### ISSUE THREAD

**Issue by JessPeterTR** [pbeshai/tidy#3]
This library is super exciting and possibly very helpful for some projects I work on!

However, I can't see from your documentation which open-source license you're using, which could prevent me from using this library at work.

Could you add more info on which open-source license you've decided to use?

**Comment by pbeshai** [comment]
ah yes, of course! I added it to at least some of the package.jsons, but I will add a LICENSE to the root.

**Comment by pbeshai** [comment]
updated with MIT license added in a LICENSE doc
