### ISSUE TITLE
Feature Request: add a boolean flag to turn on/off debug 

### ISSUE THREAD

**Issue by peterpham** [pbeshai/tidy#55]
### Feature Request

Able to turn on/off debug depending when needed. For example: I want to suppress debug on production but show it on staging

For example:
```
const _DEBUG = false;
tidy(data, debug("info label", {limit: 15, show: _DEBUG})  );
```

**Comment by pbeshai** [comment]
Hi there! You can do this with any function in a tidy flow just by making it conditional. Tidy will ignore all falsy values in the flow. e.g.

```js
const _DEBUG = false;
tidy(data, 
  _DEBUG && debug("info label", {limit: 15})  
);
// or
tidy(data, 
  _DEBUG ? debug("info label", {limit: 15}) : null 
);
```
